# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duegno',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
