# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0002_duegno_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='duegno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.Duegno'),
        ),
    ]
