# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0003_mascota_duegno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duegno',
            name='name',
        ),
        migrations.AddField(
            model_name='duegno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='duegno',
            name='first_name',
            field=models.CharField(default='Pepito', max_length=40, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duegno',
            name='last_name',
            field=models.CharField(default='Los Palotes', max_length=40, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duegno',
            name='phone',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
