# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 00:42
from __future__ import unicode_literals

import Veterinaria.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0005_auto_20171204_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duegno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='duegno',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[Veterinaria.validators.validate_chilean_cellphone]),
        ),
    ]
