# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0006_auto_20171206_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Creador'),
        ),
    ]
