# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0007_auto_20171207_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
